#!/usr/bin/python3
import sys
import math

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def factorize(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return (i, n // i)
    return None

def main():
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        return

    filename = sys.argv[1]
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factorization = factorize(n)
        if factorization is not None:
            print(f"{n}={factorization[0]}*{factorization[1]}")

if __name__ == "__main__":
    main()
